### ISSUE TITLE
Incident selector in Work screen from Disaster button

### ISSUE THREAD

**Issue by hueachilles** [CrisisCleanup/crisiscleanup-ios#4]
Given I'm on the Work screen
Then the incident selector shows the current incident by a button representing the incident disaster type

Given I'm on the Work screen
When the Incident (disaster) button is pressed
Then incidents are shown with the current incident selected in bold and in focus

Given the incident selector is open
When an incident is pressed/selected
Then the pressed incident is set as the current incident, the selector is closed, and the Incident (disaster) button is updated accordingly

**Comment by hueachilles** [comment]
![Screenshot_20230614_152758](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/8ea00833-8012-4647-b33b-b762eeae76b4)
![Screenshot_20230614_152812](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/fcd5399b-bcae-42d1-b034-f1eb71bea369)

**Comment by hueachilles** [comment]
This task was for the Work screen not the menu screen. I'm reopening.

**Comment by irineu-ad** [comment]
#17
