### ISSUE TITLE
Center map on incident bounds

### ISSUE THREAD

**Issue by hueachilles** [CrisisCleanup/crisiscleanup-ios#5]
**Focus on the map only. Ignore the buttons and overlaid text.**

Given Work screen
Then the map view shows as default

Given Work screen map view
When an incident loads or is selected
Then the map view changes bounds to encompass the current Incident's bounds

**Comment by hueachilles** [comment]
![Screenshot_20230614_154031](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/d5518d16-89f6-485d-bf11-a3cdf4f52dc0)
![Screenshot_20230614_154056](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/1d73a68d-eda1-4f54-a9a1-a6e32287a0bb)

**Comment by arroyoDev** [comment]
And it animates to that section from where it was.  Nice touch!!!!
