### ISSUE TITLE
Show number of Cases an incident has including number visible

### ISSUE THREAD

**Issue by hueachilles** [CrisisCleanup/crisiscleanup-ios#8]
**Focus on the text at the top only. Ignore the buttons.**

Given Work screen Map view
When panning an zooming the map
Then the number of cases shown/total is summarized
1. When zoomed out beyond the interactive level (dots are showing) the total number of cases shows
2. When zoomed to interactive level or closer (markers are showing)
    a. If all cases are on screen the total number of cases show
    b. If a partial number of cases are showing then show something like "`x` Cases of `y`" where `x` is the number of visible cases and `y` is the total.
    c. If no cases are visible on the map show the total number of cases.

See following for screenshots of 1, 2.a, 2.b, and 2.c.

**Comment by hueachilles** [comment]
(1) Zoomed out beyond interactive. Reads total cases.
![Screenshot_20230614_161825-dots](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/d4aa99af-c6f0-4e3c-bb9b-17b28495e293)

**Comment by hueachilles** [comment]
(2.a) All cases are on screen at interactive level. 1 total cases.
![Screenshot_20230614_161919-all](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/11e40ed2-bfa2-4692-812e-165aa10c2daf)

**Comment by hueachilles** [comment]
(2.b) A partial number of cases are visible on screen at the interactive level. 63 visible out of 876 total.
![Screenshot_20230614_161509-partial](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/2f9b8471-44af-4eac-9fe1-b65c92d0ad74)

**Comment by hueachilles** [comment]
(2.c) No cases are visible on screen. 876 total.
![Screenshot_20230614_161801-none](https://github.com/CrisisCleanup/crisiscleanup-ios/assets/7587194/d63bb1b8-e562-4c0b-8230-85d881e4c33b)

**Comment by arroyoDev** [comment]
confirmed
